export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUUCESS = "FORGOT_PASSWORD_SUUCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const FORGOT_TOKEN = "FORGOT_TOKEN";
export const FORGOT_TOKEN_SUCCESS = "FORGOT_TOKEN_SUCCECC";
export const FORGOT_TOKEN_FAILUR = "FORGOT_TOKEN_FAILUR";

export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";
export const SET_NEW_PASSWORD_SUCCESS = "SET_NEW_PASSWORD_SUCCESS";
export const SET_NEW_PASSWORD_FAILURE = "SET_NEW_PASSWORD_FAILURE";
