export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAILURE = "FACEBOOK_LOGIN_FAILURE";

export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";

export const ACCOUNT_DISABLE = "ACCOUNT_DISABLE";
export const ACCOUNT_DISABLE_SUCCESS = "ACCOUNT_DISABLE_SUCCESS";
export const ACCOUNT_DISABLE_FAILURE = "ACCOUNT_DISABLE_FAILURE";
